language: ruby
rvm:
- 2.2.5

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --assume-extension --disable-external
  - bundle exec htmlproofer ./_site --assume-extension || echo "Some External links broken..."

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false
cache: bundler
