language: ruby
# language: python
sudo: false
cache: bundler
# cache: pip
# python:
#   - '2.7'
#   - '3.6'
rvm:
  - 2.2.5

# install:
#   - pip install -r api/requirements.txt
script:
  # - green congredi -vvv
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --assume-extension --disable-external
  - bundle exec htmlproofer ./_site --assume-extension || echo "Some External links broken..."

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

# deploy:
#   provider: heroku
